### ISSUE TITLE
Install Topics Explorer on Mac OSX

### ISSUE THREAD

**Issue by pweil02** [DARIAH-DE/TopicsExplorer#123]
Hey there,
I have problems to install the Topics Explorer on Mac OSX. I updated Java, allowed al processes by hand in the settings, but the program doesnt still run. Can someone help me?

**Comment by severinsimmler** [comment]
Hi @pweil02,

are you running the source code or the standalone application? Which version of macOS are you using? Can you give some more details on the exact behavior?

**Comment by severinsimmler** [comment]
This might be related to https://github.com/pyinstaller/pyinstaller/issues/4466.

Since Apple has tightened the security regulations with macOS Catalina (10.15) for software to be executed, the Topics Explorer can currently only be used with macOS 10.14 or earlier.

**Comment by severinsimmler** [comment]
As a temporary workaraound you could install the application from source. You need Python 3.6 and have to run:

```
$ pip install pipenv --user
$ pipenv install
$ pipenv run python topicsexplorer.py
```

**Comment by AgnesKleinhans** [comment]
running on python 3.8, this worked for me:

`pip install cophi`
`pip install lda`
`python topics explorer.py`
