### ISSUE TITLE
Problem with uploading a corpus to DARIAH Topics Explorer

### ISSUE THREAD

**Issue by talvera98** [DARIAH-DE/TopicsExplorer#124]
Hello,

I'm working at a project where we want to use digital methods to analyse a corpus of German texts. 

Unfortunately, I cannot upload the corpus to Dariah. If I upload any of the prepared corpora available on TextGrid Repository, there is no problem; the program runs normally and shows the results. So it has to be a problem with my corpus, I guess. But the corpus is a plain text file and on Dariah it says it's possible to work with any of them.
A professor at my university suggested to change the coding of the text file from Windows to Unicode UTF-8. I tried that but it didn't change anything; the Topics Explorer still doesn't accept the file.

I attach a screenshot of the error message and the two text files I tried it with (In Windows coding). 

Does anyboy have an idea what the reason for the problem is? I'd be very grateful if you could take a look at my files, maybe even run them through the Topics Explorer, and could suggest what change I have to make. Thanks a lot!
![Screenshot Dariah Error](https://user-images.githubusercontent.com/70810274/92307778-0e77fa00-ef99-11ea-8d87-a7c28874ac53.jpg)
[Korpus Ev. Texte Kirche in 1Live 2019.txt](https://github.com/DARIAH-DE/TopicsExplorer/files/5178243/Korpus.Ev.Texte.Kirche.in.1Live.2019.txt)
[Korpus Kath. Texte Kirche in 1Live 2019.txt](https://github.com/DARIAH-DE/TopicsExplorer/files/5178244/Korpus.Kath.Texte.Kirche.in.1Live.2019.txt)

**Comment by severinsimmler** [comment]
Hi @talvera98,

looks like the encoding of your text files is still broken. Is the original source of the text files publicly available?

**Comment by tobimichigan** [comment]
This issue iby @talvera98  is real. I also tried several texts and it returned the error above. @severinsimmler @mromanello @reckart @thvitt

**Comment by severinsimmler** [comment]
Please make sure your text files are UTF-8 encoded, @tobimichigan.

**Comment by tobimichigan** [comment]
@severinsimmler , I later ran(**python topicsexplorer.py --browser)** with pipenv and it ran successfully. It wasn't about UTF8 encoded.
