### ISSUE TITLE
No such file topicsexplorer.py

### ISSUE THREAD

**Issue by tobimichigan** [DARIAH-DE/TopicsExplorer#128]
Hi,

Please this file:topicsexplorer.py dose not exist in any of your repos yet it is referenced in https://github.com/DARIAH-DE/TopicsExplorer
`can't open file 'topicsexplorer.py': [Errno 2] No such file or directory`
@mromanello @reckart @thvitt @MHuberFaust @tgradl

**Comment by MHuberFaust** [comment]
Hi,

the readme.md mentions the [release section](https://github.com/DARIAH-DE/TopicsExplorer/releases/tag/v2.0) which still has topicsexplorer.py.
Hope that helps :)

**Comment by pielstroem** [comment]
Hey, Michi, du lebst ja noch! Ich frage mich schon seit Monaten, wo Du inzwischen gelandet bist. Vermute mal, deinen Stud-Mail funktioniert nicht mehr, oder?

**Comment by tobimichigan** [comment]
@MHuberFaust  Thanks for your response. ..I rechecked and saw there is another folder called Source Code that is where the missing file is.
However, please try and modify the read-me file to be more clearer.
