### ISSUE TITLE
link to fiction corpus not working

### ISSUE THREAD

**Issue by jberenike** [DARIAH-DE/TopicsExplorer#131]
Hi! Thanks for this great resource! I just noticed that this URL is not operational anymore https://github.com/DARIAH-DE/TopicsExplorer/blob/master/data/british-fiction-corpus

**Comment by severinsimmler** [comment]
Hi, thanks for reporting. Fixed via https://github.com/DARIAH-DE/TopicsExplorer/commit/42dd2ba809d5e4bb4184d91042d2dce5c6776151.
