### ISSUE TITLE
download errer

### ISSUE THREAD

**Issue by pielstroem** [DARIAH-DE/TopicsExplorer#26]
Received signal 11 SEGV_MAPERR 000000000198
#0 0x7f56f81419a5 <unknown>
#1 0x7f56f6e81501 <unknown>
#2 0x7f56f8141d3d <unknown>
#3 0x7f571db1e330 <unknown>
#4 0x7f56e1cc5526 <unknown>
#5 0x7f56e1ccc62e <unknown>
#6 0x7f56e13b48db <unknown>
#7 0x7f56e13b48f9 <unknown>
#8 0x7f570182dce5 g_main_context_dispatch
#9 0x7f570182e048 <unknown>
#10 0x7f570182e0ec g_main_context_iteration
#11 0x7f570445bbaf QEventDispatcherGlib::processEvents()
#12 0x7f56e2a469a1 <unknown>
#13 0x7f570440626a QEventLoop::exec()
#14 0x7f56fde15117 QDialog::exec()
#15 0x7f56fde2638f QFileDialog::getSaveFileUrl()
#16 0x7f56fde265ba QFileDialog::getSaveFileName()
#17 0x7f56fe546487 meth_QFileDialog_getSaveFileName
#18 0x0000004a9627 _PyCFunction_FastCallKeywords
#19 0x0000005406d4 call_function
#20 0x000000545a1b _PyEval_EvalFrameDefault
#21 0x0000005402f1 _PyEval_EvalCodeWithName
#22 0x0000005411ed PyEval_EvalCodeEx
#23 0x00000048080c function_call
#24 0x000000450980 PyObject_Call
#25 0x7f56fecb8e25 PyQtSlot::call()
#26 0x7f56fecb9330 PyQtSlot::invoke()
#27 0x7f56fecb95ab PyQtSlotProxy::unislot()
#28 0x7f56fecba387 PyQtSlotProxy::qt_metacall()
#29 0x7f5704432d34 QMetaObject::activate()
#30 0x7f56fd616f3f QWebEngineProfile::downloadRequested()
#31 0x7f56fd60ec4b <unknown>
#32 0x7f56f6eb7164 <unknown>
#33 0x7f56f74a106e <unknown>
#34 0x7f56f749a739 <unknown>
#35 0x7f56f749f8a6 <unknown>
#36 0x7f56f749411a <unknown>
#37 0x7f56f81c4c19 <unknown>
#38 0x7f56f815df48 <unknown>
#39 0x7f56f815f66f <unknown>
#40 0x7f56f815fbc0 <unknown>
#41 0x7f56f6ea2805 <unknown>
#42 0x7f5704433adb QObject::event()
#43 0x7f56fdc3a54c QApplicationPrivate::notify_helper()
#44 0x7f56fdc41897 QApplication::notify()
#45 0x7f56fe685c9e sipQApplication::notify()
#46 0x7f57044079f8 QCoreApplication::notifyInternal2()
#47 0x7f570440a48b QCoreApplicationPrivate::sendPostedEvents()
#48 0x7f570445c563 <unknown>
#49 0x7f570182de04 g_main_context_dispatch
#50 0x7f570182e048 <unknown>
#51 0x7f570182e0ec g_main_context_iteration
#52 0x7f570445bbaf QEventDispatcherGlib::processEvents()
#53 0x7f56e2a469a1 <unknown>
#54 0x7f570440626a QEventLoop::exec()
#55 0x7f570440eda4 QCoreApplication::exec()
#56 0x7f56fe5113e0 meth_QApplication_exec_
#57 0x0000004a94a9 _PyCFunction_FastCallKeywords
#58 0x0000005406d4 call_function
#59 0x00000054552c _PyEval_EvalFrameDefault
#60 0x00000053f681 _PyFunction_FastCall
#61 0x000000540817 call_function
  r8: 0000000000000000  r9: 0000000000000000 r10: 00007f571d3fbc8c r11: 0000000000000001
 r12: 0000000000000000 r13: 0000000007d42880 r14: 0000000007f33f40 r15: 0000000000000000
  di: 0000000007f65b30  si: 0000000000000000  bp: 0000000007f65b30  bx: 0000000007eaa7a0
  dx: 0000000007f33f40  ax: 0000000000000001  cx: 0000000007eaa7a0  sp: 00007fff538fab50
  ip: 00007f56e1cc5526 efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000198
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by severinsimmler** [comment]
Hopefully fixed in https://github.com/DARIAH-DE/TopicsExplorer/commit/0f6738c84334c5ee0470bb718032f7ea28f168dc.
