### ISSUE TITLE
add a way to download created files during the modelling process

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/TopicsExplorer#7]
make a zip file downloadable including file for configuration, doc-topic, topic-key, key-weight?, static visualisation?

**Comment by severinsimmler** [comment]
All produced files will be saved as a ZIP archive in the current working directory by default.

## Todo
Do not save the files automatically, but offer a button that triggers the saving.

**Comment by severinsimmler** [comment]
```python
@app.route('/model/download') 
def download_generated_data():
    return send_file(pathlib.Path(tempdir, 'topicmodeling.zip'),  # dump it to static folder?
                              mimetype='???',  # is there a mimetype for ZIP archives?
                              attachment_filename='topicmodeling.zip',
                              as_attachment=True)
```

**Comment by severinsimmler** [comment]
https://stackoverflow.com/questions/42887955/how-to-download-files-using-pyqt5-webenginewidgets

**Comment by severinsimmler** [comment]
If I merge testing into master, the issue will close. When the download button is pressed, the ZIP archive is automatically saved to the download folder. So it doesn't open a dialog or anything, like in a normal browser. Implementing such a dialog would be an extension for a later release.

Here is an example for a download manager in C++: http://doc.qt.io/qt-5/qtnetwork-downloadmanager-downloadmanager-cpp.html

One could translate that into Python or something. No idea.

**Comment by severinsimmler** [comment]
https://github.com/pycom/EricShort/tree/master/Helpviewer/Download

**Comment by thvitt** [comment]
Isn't a call to  `QFileDialog.getSaveFileName` enough?

**Comment by severinsimmler** [comment]
Great, thank you! Exactly what I was looking for :)
