### ISSUE TITLE
Windows: fetching stopwords in app context

### ISSUE THREAD

**Issue by severinsimmler** [DARIAH-DE/TopicsExplorer#85]

**Comment by gnmarten** [comment]
selecting an external file with stopwords (as recommended by the app) rather than the internal stopwords causes the app to throw an I/O error

**Comment by severinsimmler** [comment]
Thank you for this bug report, @gnmarten. This has been fixed in [v2.0.1](https://github.com/DARIAH-DE/TopicsExplorer/releases/tag/v2.0), (and was only a Windows bug).
